global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'order-service'

  - job_name: 'inventory-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3001']
        labels:
          service: 'inventory-service'

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3002']
        labels:
          service: 'payment-service'
          
  - job_name: 'activity-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3005']
        labels:
          service: 'activity-service'
          
  - job_name: 'fraud-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3006']
        labels:
          service: 'fraud-service'
          
  - job_name: 'analytics-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3007']
        labels:
          service: 'analytics-service'